Image Embedder C Tasks API
google/mediapipe pull request #4943
Opened 2023-11-07 15:04 UTC by kinaryml

- Add the files necessary to implement the Image Embedder C API
- Add a utility to compute similarity between two embeddings (for text and vision tasks)

2023-11-07 17:17 UTC, schmidt-sebastian requested changes

2023-11-07 17:17 UTC, schmidt-sebastian commented on mediapipe/tasks/c/components/containers/embedding_result_converter.cc
> +    out->head_name = std::make_optional(std::string(in.head_name));
Make_optional shouldn't be needed as this should be converted during assignment.

2023-11-07 17:17 UTC, schmidt-sebastian commented on mediapipe/tasks/c/components/containers/embedding_result_converter.h
> +void ConvertToCppEmbedding(
This is a C++ function so it should start with Cpp, even though `CppConvertToCppEmbedding` is not going to win us any awards :)

2023-11-07 17:17 UTC, schmidt-sebastian commented on mediapipe/tasks/c/text/text_embedder/text_embedder.h
> +MP_EXPORT int cosine_similarity(const Embedding& u, const Embedding& v,
Think we should prefix this with "text_embedder_" so we don't get duplicate symbol errors.

2023-11-07 17:17 UTC, schmidt-sebastian commented on mediapipe/tasks/c/vision/image_embedder/image_embedder.h
> +// Supported image formats.
This needs to be moved to a common file for all image tasks.

2023-11-07 17:17 UTC, schmidt-sebastian commented on mediapipe/tasks/c/vision/image_embedder/image_embedder.h
> +MP_EXPORT int image_embedder_embed_for_video(void* embedder,
We should add comments here (and in the image classifier as well).

2023-11-07 17:17 UTC, schmidt-sebastian commented on mediapipe/tasks/c/vision/image_embedder/image_embedder.h
> +MP_EXPORT int cosine_similarity(const Embedding& u, const Embedding& v,
Prefix with image_embedder to avoid duplicate symbol names.

2023-11-07 22:24 UTC, kinaryml commented
@schmidt-sebastian I've resolved those comments. PTAL.

2023-11-08 17:01 UTC, schmidt-sebastian approved these changes

2023-11-08 20:35 UTC, merged