Added iOS Image Embedder Options, Result, Helpers and Header
google/mediapipe pull request #5012
Opened 2023-12-06 16:06 UTC by priankakariatyml

2023-12-15 14:56 UTC, priankakariatyml commented
@schmidt-sebastian PR for Image Embedder

2023-12-18 22:00 UTC, schmidt-sebastian requested changes
Thank you! Can you add the cosine similarity API that we use in Text Embedder?

2023-12-18 22:00 UTC, schmidt-sebastian commented on mediapipe/tasks/ios/vision/image_embedder/sources/MPPImageEmbedder.h
> + * 2. kCVPixelFormatType_32RGBA
Nit: Need to update to new phrasing.

2023-12-18 22:00 UTC, schmidt-sebastian commented on mediapipe/tasks/ios/vision/image_embedder/sources/MPPImageEmbedder.h
> +- (instancetype)init NS_UNAVAILABLE;
We should have a cosine similarity API as well: https://github.com/google/mediapipe/blob/master/mediapipe/tasks/python/vision/image_embedder.py#L339

2024-01-02 02:01 UTC, schmidt-sebastian approved these changes

2024-01-05 00:31 UTC, merged